repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.4
  hooks:
    - id: ruff
      args: ["--fix"]
      exclude: ^(demos/|tests/examples/)
    - id: ruff-format
      exclude: ^(demos/|tests/examples/)

- repo: https://github.com/pycqa/bandit
  rev: 1.7.9
  hooks:
    - id: bandit
      args: ["-q", "-r", "services", "packages"]
      exclude: ^tests/

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.4
  hooks:
    - id: gitleaks
      args: ["--no-banner", "protect", "--staged"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: check-merge-conflict
    - id: debug-statements

- repo: local
  hooks:
    - id: generate-openapi
      name: Generate OpenAPI specification
      entry: bash -c 'if python3 -c "import fastapi" 2>/dev/null; then python3 scripts/generate_openapi.py; else echo "⚠️  Skipping OpenAPI generation - FastAPI not available in environment"; fi'
      language: system
      files: ^services/api/
      pass_filenames: false
