global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # RAGline Worker Metrics
  - job_name: 'ragline-worker'
    static_configs:
      - targets: ['host.docker.internal:8081']
    scrape_interval: 15s
    metrics_path: /metrics

  # RAGline API Metrics (if available)
  - job_name: 'ragline-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 30s
    metrics_path: /metrics

  # RAGline LLM Service Metrics (if available)
  - job_name: 'ragline-llm'
    static_configs:
      - targets: ['host.docker.internal:8001']
    scrape_interval: 30s
    metrics_path: /metrics

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alerting configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
